# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: db
spec:
  storageClassName: manual  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi