# mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: db
spec:
  storageClassName: manual  # Match the PV's storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi