apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 8080  # Container port (should match Flask app)
      nodePort: 30000 # Expose on port 30000
